name    'jcannon-ovirt'
version '0.0.4'
source 'git://github.com/jasonc/puppet-ovirt.git'
author 'jcannon'
summary 'A puppet module to install oVirt.'
description 'A puppet module to install oVirt.'
project_page 'https://github.com/jasonc/puppet-ovirt'
